### PR TITLE
fix `include_debug_symbols` doesn't work unless explicitly set

### LINKED ISSUE #16: `include_debug_symbols` doesn't work unless explicitly set
Even though the `include_debug_symbols` parameter defaults to `true`, if omitted, debug symbols will not be included in the `.xcframework` file. 

I tested in https://github.com/RevenueCat/purchases-ios adding and removing the parameter [here](https://github.com/RevenueCat/purchases-ios/blob/main/fastlane/Fastfile#L351). 

I don't believe this is the expected behavior given that the parameter defaults to `true`, but happy to close if this was indeed the expected behavior.

### PR DESCRIPTION
**Pull request by aboedo**
Fixes #16 

# Changes
If the `include_debug_symbols` parameter is omitted, debug symbols will be included in the `.xcframework` folder by default.

## References
- #16 

## Risks
- [ ] None
- [X] Low
- [ ] High

I consider this low risk, since it would only add files to the `.xcframework` folder, it would only affect projects that are omitting the parameter, and it's what I would have considered expected behavior since the parameter defaults to true according to the docs. 

Happy to close if the previous behavior was expected, though!! 
And let me know if I missed anything.

### CODE REVIEW

File: spec/fastlane_create_xcframework_action_spec.rb [hunk 1]
```diff
@@ -217,6 +217,20 @@
         expect(result).to eq(expected_result)
       end
 
+      it 'verifies debug_symbols method when :include_debug_symbols option was not provided' do
```
Comment (aboedo) [inline spec/fastlane_create_xcframework_action_spec.rb:220]: This test is basically the same code as `it 'verifies debug_symbols method'`, but without passing in the param. And it fails on the default branch currently

**Comment by bielikb** [comment]
Nica catch! 
Thanks @aboedo!

Ill review this work in upcoming days ;)

**Review by bielikb — APPROVED** [review]
Looks good. Thanks!
